orders/urls.py
from django.urls import path
from orders.views import (
    OrderCreateView,
    SuccessTemplateView,
    CancelTemplateView,
    OrderListView,
    OrderDetailView,
)

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
    path("order-success/", SuccessTemplateView.as_view(), name="order-success"),
    path("order-canceled/", CancelTemplateView.as_view(), name="order-canceled"),
    path("", OrderListView.as_view(), name="orders"),
    path("order/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
]

app_name = "orders"

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import IndexView
from orders.views import stripe_webhook_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("webhook/", stripe_webhook_view, name="stripe-webhook"),
    path("accounts/", include("allauth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from users.views import (
    UserLoginView,
    UserRegisterView,
    UserProfileView,
    logout,
    EmailVerificationView,
)

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/", login_required(UserProfileView.as_view()), name="profile"),
    path("logout/", logout, name="logout"),
    path(
        "verify/<str:email>/<uuid:code>/",
        EmailVerificationView.as_view(),
        name="verify_email",
    ),
]


app_name = "users"

orders/models.py
from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    CREATED, PAID = 0, 1
    STATUSES = (
        (CREATED, "Created"),
        (PAID, "Paid"),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=255)
    address = models.CharField(max_length=255)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order #{self.id}.{self.first_name} {self.last_name}"

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            "purchased_items": [basket.de_json() for basket in baskets],
            "total_sum": float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "John"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Lol"})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "you@example.com"}
        )
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "NY, Park"}
        )
    )

    class Meta:
        model = Order
        fields = ["first_name", "last_name", "email", "address"]

orders/views.py
import stripe

from http import HTTPStatus
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Basket

stripe.api_key = settings.STRIPE_SECRET_KEY
endpoint_secret = settings.STRIPE_WEBHOOK_SECRET


class SuccessTemplateView(TitleMixin, generic.TemplateView):
    template_name = "orders/success.html"
    title = "Store - tnx for order!"


class CancelTemplateView(TitleMixin, generic.TemplateView):
    template_name = "orders/cancel.html"
    title = "Something wrong =("


class OrderListView(TitleMixin, generic.ListView):
    template_name = "orders/orders.html"
    title = "Store - Orders"
    queryset = Order.objects.all()

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(generic.DetailView):
    template_name = "orders/order.html"
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context["title"] = f"Store - Order #{self.object.id}"
        return context


class OrderCreateView(TitleMixin, generic.CreateView):
    template_name = "orders/order-create.html"
    form_class = OrderForm
    success_url = reverse_lazy("orders:create")
    title = "Store - Create Order"

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={"order_id": self.object.id},
            mode="payment",
            success_url=f"{settings.DOMAIN_NAME}{reverse('orders:order-success')}",
            cancel_url=f"{settings.DOMAIN_NAME}{reverse('orders:order-canceled')}",
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/cancel.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}


{% block content %}
  <section>
    <div class="alert alert-warning text-center" role="alert">
      Please fill in your email address.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Checkout</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Basket</span>
                    <span class="badge badge-primary badge-pill text-white">{{ basket.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                  {% for item in basket %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                          <div>
                              <h6 class="my-0"> {{ item.product.name }}</h6>
                              <small class="text-muted">{{ item.quantity }}</small>
                          </div>
                          <span class="text-muted">{{ item.sum }} $.</span>
                      </li>
                  {% endfor %}
                  <li class="list-group-item d-flex justify-content-between">
                      <span>Amount payable</span>
                      <strong>{{ basket.total_sum }} $</strong>
                  </li>

                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Delivery address</h4>
                <form action="{% url 'orders:create' %}" method="post">
                  {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">First name</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                            {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Next</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
  <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Order №{{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Product name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    {% for purchased_item in object.basket_history.purchased_items %}
                        <tr>
                            <th scope="row">
                                {{ purchased_item.product_name }}
                            </th>
                            <td>{{ purchased_item.quantity }}</td>
                            <td>{{ purchased_item.price|intcomma }} $</td>
                            <td>{{ purchased_item.sum| intcomma }} $ </td>
                        </tr>
                    {% endfor %}
                    <tbody>
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Total : {{ object.basket_history.total_sum|intcomma }} $</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
  <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Orders</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Created</th>
                        <th scope="col">Total </th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                      <tr class="table-info">
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.created | naturaltime }}</td>
                        <td>{{ order.basket_history.total_sum| intcomma }} $</td>
                        <td>
                            <a href="{% url 'orders:order-detail' order.id %}">See details</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'users/base.html' %}
{% block content %}
  <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Thanks for order</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Your order has been successfully completed.<br>
                                </h4>
                            </div>
                            <div class="text-center font-weight-light my-4" >
                              <a class="btn btn-info"
                                       href="{% url 'users:profile' %}">Back to site
                              </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}